"""create initial legal spend schema

Revision ID: 334757f7b99a
Revises: 
Create Date: 2026-08-07 11:48:19.915710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '334757f7b99a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert',
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('alert_id'), if_not_exists=True
    )
    op.create_table('audit_log',
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timestamp', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('log_id'), if_not_exists=True
    )
    op.create_table('budget_ledger',
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('entry_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ledger_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ledger_id'), if_not_exists=True
    )
    op.create_table('firm',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('firm_id'), if_not_exists=True
    )
    op.create_table('invoice',
    sa.Column('matter_id', sa.Integer(), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.Column('invoice_no', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('invoice_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('invoice_id'), if_not_exists=True
    )
    op.create_table('line_item',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('timekeeper', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hours', sa.Float(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('line_item_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('line_item_id'), if_not_exists=True
    )
    op.create_table('user',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'), if_not_exists=True
    )
    op.create_table('matter',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('matter_id', sa.Integer(), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firm.firm_id'], ),
    sa.PrimaryKeyConstraint('matter_id'), if_not_exists=True
    )
    op.create_table('budget',
    sa.Column('allocated_amt', sa.Float(), nullable=False),
    sa.Column('threshold_pct', sa.Float(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('matter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['matter_id'], ['matter.matter_id'], ),
    sa.PrimaryKeyConstraint('budget_id'),
    sa.UniqueConstraint('matter_id'), if_not_exists=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('budget')
    op.drop_table('matter')
    op.drop_table('user')
    op.drop_table('line_item')
    op.drop_table('invoice')
    op.drop_table('firm')
    op.drop_table('budget_ledger')
    op.drop_table('audit_log')
    op.drop_table('alert')
    # ### end Alembic commands ###
